import type { Database } from "./types";

const CDN = "https://cdn.prod.website-files.com";
const BASE = `${CDN}/670010141e02b62e6f054e13`;
const CMS = `${CDN}/6704d32b156a64ece7cc9779`;

export const seedDatabase = (): Database => {
  const now = new Date().toISOString();

  const categories = [
    {
      id: "cat_eco",
      name: "Eco-Friendly Homes",
      slug: "eco-friendly-homes",
      description:
        "Sustainable living in eco-friendly homes equipped with cutting-edge green technologies.",
      image: `${CMS}/6717b267b623870f9fafa704_p-categories-thumb-1.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat_commercial",
      name: "Commercial Properties",
      slug: "commercial-properties",
      description:
        "Commercial buildings intended to provide visitors with comfort and convenience.",
      image: `${CMS}/6717b2766adb5216ec4d552d_p-categories-thumb-2.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat_luxury",
      name: "Luxury Properties",
      slug: "luxury-properties",
      description:
        "Elegant life in opulent mansions and estates equipped with the best conveniences.",
      image: `${CMS}/6717b28870bd5fbc0a99baf6_p-categories-thumb-3.jpg`,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const agents = [
    {
      id: "agent_1",
      name: "Bryce Jones",
      title: "Client relations manager",
      email: "bryce@realfy.com",
      phone: "(555) 100-1001",
      bio: "Helping clients find homes that match their lifestyle.",
      image: `${CMS}/6709188127b55df89d439264_agents-thumb-1.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "agent_2",
      name: "Dentista Aguilda",
      title: "Luxury property expert",
      email: "dentista@realfy.com",
      phone: "(555) 100-1002",
      bio: "Specialist in high-end residential listings.",
      image: `${CMS}/6709268e668c86b5b1862dc2_agents-thumb-2.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "agent_3",
      name: "Agustín Trabajo",
      title: "Lead property advisor",
      email: "agustin@realfy.com",
      phone: "(555) 100-1003",
      bio: "Guiding buyers through every step of the purchase.",
      image: `${CMS}/6709271fadee83ccbf78ce61_agents-thumb-3.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "agent_4",
      name: "Cristela Estilista",
      title: "Senior real estate consultant",
      email: "cristela@realfy.com",
      phone: "(555) 100-1004",
      bio: "Trusted advisor for residential and investment deals.",
      image: `${CMS}/67092736c257ad43bc59d04c_agents-thumb-4.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "agent_5",
      name: "Denya Contadora",
      title: "Real estate investment specialist",
      email: "denya@realfy.com",
      phone: "(555) 100-1005",
      bio: "Focused on ROI-driven property investments.",
      image: `${CMS}/67092753708e26b2cc914f71_agents-thumb-5.jpg`,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "agent_6",
      name: "Alday Banamex",
      title: "Residential sales consultant",
      email: "alday@realfy.com",
      phone: "(555) 100-1006",
      bio: "Making homeownership simple and clear.",
      image: `${CMS}/67092767c483e212c03ed4b0_agents-thumb-6.jpg`,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const properties = [
    {
      id: "prop_1",
      title: "Sunset luxury villa",
      slug: "sunset-luxury-villa",
      description:
        "A stunning coastal villa with panoramic sunset views, open living spaces, and private outdoor entertaining areas.",
      address: "12273 Dream Avenue",
      city: "New York",
      state: "NY",
      price: 400,
      listingType: "rent" as const,
      categoryId: "cat_luxury",
      bedrooms: 3,
      bathrooms: 2,
      parking: 2,
      sqft: 1490,
      images: [`${CMS}/67091f3f674dafa04e4277ef_properties-thumb-1.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_2",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_2",
      title: "Parkview estates",
      slug: "parkview-estates",
      description:
        "Spacious family estate overlooking green parkland with modern finishes throughout.",
      address: "2972 Westheimer Rd.",
      city: "Santa Ana",
      state: "IL",
      price: 50000,
      listingType: "sell" as const,
      categoryId: "cat_luxury",
      bedrooms: 4,
      bathrooms: 3,
      parking: 2,
      sqft: 2370,
      images: [`${CMS}/6709283c5fcf7ca778f668db_properties-thumb-2.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_3",
      title: "Cedar grove residences",
      slug: "cedar-grove-residences",
      description:
        "Comfortable residence surrounded by mature trees in a quiet neighborhood.",
      address: "8502 Preston Rd.",
      city: "Inglewood",
      state: "ME",
      price: 200,
      listingType: "rent" as const,
      categoryId: "cat_eco",
      bedrooms: 3,
      bathrooms: 3,
      parking: 1,
      sqft: 1300,
      images: [`${CMS}/67092921093f2a8744d6aa23_properties-thumb-3.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_3",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_4",
      title: "Lakeside manor",
      slug: "lakeside-manor",
      description:
        "Charming lakeside home with serene water views and a cozy floor plan.",
      address: "2464 Royal Ln.",
      city: "Mesa",
      state: "NJ",
      price: 32000,
      listingType: "sell" as const,
      categoryId: "cat_eco",
      bedrooms: 2,
      bathrooms: 1,
      parking: 1,
      sqft: 700,
      images: [`${CMS}/6709299d5bb93f90a2d4a161_properties-thumb-4.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_4",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_5",
      title: "Oceanfront oasis",
      slug: "oceanfront-oasis",
      description:
        "Wake up to ocean breezes in this bright coastal retreat near the beach.",
      address: "6391 Elgin St.",
      city: "Celina",
      state: "DE",
      price: 520,
      listingType: "rent" as const,
      categoryId: "cat_luxury",
      bedrooms: 3,
      bathrooms: 3,
      parking: 2,
      sqft: 1500,
      images: [`${CMS}/670929e5c257ad43bc5c68d7_properties-thumb-5.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_5",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_6",
      title: "Skyline tower",
      slug: "skyline-tower",
      description:
        "Contemporary city living with skyline views and walkable amenities.",
      address: "2715 Ash Dr.",
      city: "San Jose",
      state: "SD",
      price: 360,
      listingType: "rent" as const,
      categoryId: "cat_commercial",
      bedrooms: 3,
      bathrooms: 2,
      parking: 1,
      sqft: 1250,
      images: [`${CMS}/67092a3483ab9e9a310b114f_properties-thumb-6.jpg`],
      featured: true,
      status: "published" as const,
      agentId: "agent_6",
      createdAt: now,
      updatedAt: now,
    },
  ];

  return {
    categories,
    properties,
    agents,
    leads: [
      {
        id: "lead_1",
        name: "Jordan Lee",
        email: "jordan@example.com",
        phone: "(555) 222-3344",
        message: "Interested in scheduling a tour for Sunset luxury villa.",
        propertyId: "prop_1",
        status: "new",
        source: "website",
        createdAt: now,
        updatedAt: now,
      },
    ],
    media: [],
    settings: {
      brandName: "KeyNestOS",
      tagline: "Buy & Sell Your dream",
      heroTitle: "Real-Estate",
      aboutHeading: "The ideal way to find your dream home",
      aboutText:
        "Wake up to the sound of waves and the smell of salt air in one of our stunning coastal homes. Perfect for those seeking a serene escape, these properties offer unmatched ocean views and direct beach safe neighborhoods, and nearby schools access.",
      aboutImage: `${BASE}/67014ccc08fb3aa6c87cb90d_about-thumb-1.jpg`,
      stats: [
        {
          label: "Properties",
          value: "200+",
          description:
            "Discover the key figures that highlight our impact in the real estate market. From satisfied clients to successful transactions",
        },
        {
          label: "Satisfied Users",
          value: "300+",
          description:
            "Take a closer look at the statistics that reflect our growth, success, and dedication to helping clients achieve their real estate goals.",
        },
        {
          label: "Happy Clients",
          value: "100%",
          description:
            "From closed deals to client satisfaction ratings, our numbers showcase the impact we’ve made in the real estate industry",
        },
        {
          label: "Follower",
          value: "900K",
          description:
            "Explore the numbers behind our real estate success, showcasing the trust clients place in us and the results we consistently deliver.",
        },
      ],
    },
  };
};

export const ASSETS = {
  logo: `${BASE}/672b0cbffbb01b1ebb84e214_Realfy.svg`,
  footerLogo: `${BASE}/672b0c705f082c0c17a2c1dc_f-logo.svg`,
  hero: "/hero-pool.jpg",
  choose: `${BASE}/67160aef4db775dfa018cac7_choose-thumb-1.jpg`,
  footer: `${BASE}/67120964815745137dc8e366_footer-thumb-2.png`,
  process: [
    `${BASE}/67018c77e82d41323b7c69ca_process-thumb-1.jpg`,
    `${BASE}/67018c7528a69477c950bea9_process-thumb-2.jpg`,
    `${BASE}/67018c75a96327a0b77b36e9_process-thumb-3.jpg`,
  ],
  testimonials: [
    `${BASE}/670224e217d36d0f9d6431a3_testimonials-thumb-1.jpg`,
    `${BASE}/670224e2dba4f045e5fbe423_testimonials-thumb-2.jpg`,
    `${BASE}/670224e2671d7cf571ff35b2_testimonials-thumb-3.jpg`,
  ],
  blog: [
    `${CMS}/67092f6513d7a3c1a18934c6_blog-thumb-10.jpg`,
    `${CMS}/67092f8dcaadf9e4eb92d372_blog-thumb-11.jpg`,
    `${CMS}/67092ffb13d7a3c1a189b27e_blog-thumb-12.jpg`,
  ],
};
